### PR TITLE
Account for auth_urls with trailing slash

### LINKED ISSUE #114: Issue with OS_AUTH_URL with a trailing slash
Hello Dmitry!
I can't access containers in a named region.

Here's what I source before running my code:
```sh
#!/bin/bash
export OS_AUTH_URL=https://auth.cloud.ovh.net/v3/
export OS_IDENTITY_API_VERSION=3
export OS_USER_DOMAIN_NAME='Default'
export OS_PROJECT_DOMAIN_NAME='Default'
export OS_PROJECT_ID='<redacted>'
export OS_USERNAME='<redacted>'
export OS_PASSWORD='<redacted>'
export OS_REGION_NAME='DE'
```

My code:
```rust
# src/main.rs
extern crate openstack;

fn cloud_from_env() -> openstack::Result<openstack::Cloud> {
    let mut cloud = openstack::Cloud::from_env()?;
    {
        let filters = cloud.endpoint_filters_mut();
        filters.set_region("DE");
    }
    Ok(cloud)
}

fn main() {
    let os = cloud_from_env().expect("Failed to create an identity provider from the environment");

    let containers = os.list_containers();

    println!("Name: {:?}", containers);
}
```

Gives:
```plaintext
Name: Err(Error { kind: ResourceNotFound, message: "The resource could not be found.", status: Some(404) })
```

In the same shell (with the same env) `openstack container list` gives one result.

What am I doing wrong?

### PR DESCRIPTION
**Pull request by pierreprinetti**
Prior to this patch, auth_urls ending in `/v3/` produced malformed auth
token endpoints.

Fixes https://github.com/dtantsur/rust-openstack/issues/114

---
This patch may induce pain in Rustacean eyes.

Please be merciful

### CODE REVIEW

File: src/identity.rs [hunk 1]
```diff
@@ -222,12 +222,19 @@ impl Password {
         S3: Into<String>,
     {
         let url = auth_url.into_url()?;
-        // TODO: more robust logic?
-        let token_endpoint = if url.path().ends_with("/v3") {
-            format!("{}/auth/tokens", url)
+
+        let token_endpoint = if url.path().ends_with("/") {
```
Comment (dtantsur) [inline src/identity.rs]: I think it can be done a bit nicer with something like
```rust
let mut url = auth_url.into_url()?;
url.path_segments_mut().map_err(|_| <figure out something>).pop_if_empty();
```

**Comment by pierreprinetti** [comment]
I tried to implement your proposed alternative, and I hit these obstacles:
* I am worried about the side effects of mutating `url` (and even more so because I am under the impression that the OpenStack endpoints love trailing slashes)
* assigning the `PathSegmentsMut` to `token_endpoint` instead means that I reassign it like 3 times :/

Eventually, everything really boils down to making sure that there is `v3` before appending `auth/tokens`. It would be easier if `Url::join` wasn't so picky about trailing slashes.

Can we find a less invasive beautification solution for my procedural horror? Maybe using some magic method of the Iterator?

```rust
        let token_endpoint = url
            .path_segments()
            .ok_or(|_| "throw some error")?
            .last_is_or_add("v3")  // <-- this does not exist
            .extend("auth", "tokens");
```

**Comment by pierreprinetti** [comment]
OK, I think that I have made the change you requested.

File: src/error.rs [hunk 2]
```diff
@@ -207,6 +207,15 @@ impl From<HttpClientError> for Error {
     }
 }
 
+impl From<&str> for Error {
```
Comment (dtantsur) [inline src/error.rs]: I see where you're coming from here, but I'd prefer to avoid that since this can be easily misused.

File: src/identity.rs [hunk 3]
```diff
@@ -221,13 +221,19 @@ impl Password {
         S2: Into<String>,
         S3: Into<String>,
     {
-        let url = auth_url.into_url()?;
-        // TODO: more robust logic?
-        let token_endpoint = if url.path().ends_with("/v3") {
+        let mut url = auth_url.into_url()?;
+
+        let _p = url
```
Comment (dtantsur) [inline src/identity.rs]: very nit: usually just `_` is used for throw-away variables

File: src/identity.rs [hunk 4]
```diff
@@ -221,13 +221,19 @@ impl Password {
         S2: Into<String>,
         S3: Into<String>,
     {
-        let url = auth_url.into_url()?;
-        // TODO: more robust logic?
-        let token_endpoint = if url.path().ends_with("/v3") {
+        let mut url = auth_url.into_url()?;
```
Comment (dtantsur) [inline src/identity.rs:224]: Note: `url` is a local variable, mutating it is totally fine.

File: src/identity.rs [hunk 5]
```diff
@@ -221,13 +221,19 @@ impl Password {
...
+
+        let _p = url
+            .path_segments_mut()
+            .map_err(|_| "cannot be base")?
```
Comment (dtantsur) [inline src/identity.rs]: I'd prefer to avoid relying on an implicit conversion from a string to `Error`, let's use `Error::new(ErrorKind::InvalidConfig, "Invalid auth_url:  wrong schema?")` or something like that.

File: src/identity.rs [hunk 6]
```diff
@@ -540,4 +546,88 @@ pub mod test {
         );
         assert_eq!(id.endpoint_filters().region, None);
     }
+
+    #[test]
+    fn test_token_endpoint_with_trailing_slash() {
```
Comment (dtantsur) [inline src/identity.rs:551]: Huge thanks for adding tests!

**Review by dtantsur — CHANGES_REQUESTED** [review]
Hey, this is looking great! The only problem I have is with the implicit conversion from `&str` to `Error`, I'd avoid it as a potential foot-shooting opportunity.

File: src/identity.rs (hunk 5 above)
Comment (pierreprinetti) [reply src/identity.rs]: oh cool, thanks!

File: src/identity.rs (hunk 3 above)
Comment (pierreprinetti) [reply src/identity.rs]: Good to know! Fixed :)

All these segment:: methods return _self_. The compiler complains if I don't use it, so I thought about assigning to `_`. Is this the recommended way around the problem?

File: src/identity.rs (hunk 4 above)
Comment (pierreprinetti) [reply src/identity.rs:224]: Are you not concerned that for the purpose of building the `tokens` URL, we are changing the base auth_url (stripping the trailing slash from `Password::auth_url()`)?

cf:
https://github.com/dtantsur/rust-osauth/pull/14/files#diff-3d59bc47b6ad2d1cb1349abf34de2280R620

Comment (dtantsur) [reply src/identity.rs:224]: Nope. Actually, one of the cool things about Rust is that it makes tracking such things easier. `IntoUrl.into_url` returns a `Url`, not a `&mut Url`, so we're mutating a local variable.

**Review by dtantsur — APPROVED** [review]
recheck

**Comment by dtantsur** [comment]
recheck

**Comment by dtantsur** [comment]
devstack is broken on rocky and queens, I think this is fine to proceed
